version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=471431566659.dkr.ecr.us-east-1.amazonaws.com/mydeveloperplanet/myawsplanet
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Building the docker image...
      - mvn clean verify
      - docker tag mydeveloperplanet/myawsplanet:0.0.1-SNAPSHOT $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing the docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"ITEX-PAYWISE-PROD-CONT","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
